services:
  api:
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://root:root@postgres:5432/root?schema=public
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - 3000:3000
    networks:
      - consumption-api-network
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - consumption-api-network

volumes:
  postgres_data:

networks:
  consumption-api-network:
    driver: bridge
