services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: ["dockerize", "-wait", "tcp://postgres:5432", "-timeout", "20s", "sh", "-c", "npx prisma migrate deploy && npm run start:dev"]
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://root:root@postgres:5432/root?schema=public
      API_URL: http://localhost:3000
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    networks:
      - consumption-api-network
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - consumption-api-network

volumes:
  postgres_data:

networks:
  consumption-api-network:
    driver: bridge
